version: "3.9"

services:
  node-api:
    image: hafizku-node-api:latest
    container_name: hafizku-node-api
    command: npm run start
    env_file:
      - .env
    depends_on:
      - postgres-db
    restart: always
    networks:
      - hafizku-net

  python-api:
    image: hafizku-python-api:latest
    container_name: hafizku-python-api
    command: python main.py
    env_file:
      - .env
    depends_on:
      - postgres-db
    restart: always
    networks:
      - hafizku-net

  postgres-db:
    image: postgres:15-alpine
    container_name: hafizku-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - hafizku-net

  nginx:
    image: nginx:alpine
    container_name: hafizku-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-api
      - python-api
    restart: always
    networks:
      - hafizku-net

networks:
  hafizku-net:
    driver: bridge

volumes:
  postgres_data:
