services:
  node-api:
    image: ghcr.io/hafizku/node-api:latest # Menggunakan image dari GHCR
    container_name: hafizku-node-api
    restart: always # Penting agar container nyala otomatis jika server restart
    command: npm run start # Menggunakan mode production
    env_file:
      - .env
    depends_on:
      - postgres-db
    # Volume hanya untuk folder media/upload, bukan source code
    volumes:
      - ./hafizku-media:/app/public/recordings
    networks:
      - hafizku-net

  python-api:
    image: ghcr.io/hafizku/python-api:latest
    container_name: hafizku-python-api
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres-db
    volumes:
      - ./hafizku-media:/app/public/recordings
    networks:
      - hafizku-net

  postgres-db:
    image: postgres:15-alpine
    container_name: hafizku-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hafizku-net

  nginx:
    image: nginx:alpine
    container_name: hafizku-nginx
    restart: always
    ports:
      - "80:80" # Standar web port
      - "443:443" # Untuk SSL nantinya
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # :ro artinya read-only
      - ./hafizku-media:/var/www/html/recordings:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - node-api
      - python-api
    networks:
      - hafizku-net

  certbot:
    image: certbot/certbot
    container_name: hafizku-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - hafizku-net

networks:
  hafizku-net:
    driver: bridge

volumes:
  postgres_data:
