services:
  node-api:
    build: ./node-api
    depends_on:
      - postgres-db
      # - mongo-db
    volumes:
      - ./node-api:/app
      - /app/node_modules
    networks:
      - hafizku-net

  python-api:
    build: ./python-api
    depends_on:
      - postgres-db
      # - mongo-db
    volumes:
      - ./python-api:/app
    networks:
      - hafizku-net

  postgres-db:
    image: postgres:15-alpine
    container_name: hafizku-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432" # Agar bisa diakses dari aplikasi GUI seperti DBeaver/TablePlus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hafizku-net

  # mongo-db:
  #   image: mongo:latest
  #   container_name: hafizku-mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  #   ports:
  #     - "27017:27017" # Agar bisa diakses dari MongoDB Compass
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     - hafizku-net

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-api
      - python-api
    networks:
      - hafizku-net

networks:
  hafizku-net:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
