services:
  node-api:
    build: ./node-api
    container_name: hafizku-node-api
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - postgres-db
    volumes:
      - ./node-api:/app
      - /app/node_modules
    networks:
      - hafizku-net

  python-api:
    build:
      context: ./python-api
    container_name: hafizku-python-api
    env_file:
      - .env
    depends_on:
      - postgres-db
    volumes:
      - ./python-api:/app
      - ./hafizku-media:/app/public/recordings
    networks:
      - hafizku-net

  postgres-db:
    image: postgres:15-alpine
    container_name: hafizku-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432" # Agar bisa diakses dari aplikasi GUI seperti DBeaver/TablePlus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hafizku-net

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./hafizku-media:/var/www/html/recordings
    depends_on:
      - node-api
      - python-api
    networks:
      - hafizku-net

networks:
  hafizku-net:
    driver: bridge

volumes:
  postgres_data:
